### ISSUE TITLE
Part 3 - Blog post missing code

### ISSUE THREAD

**Issue by Exadra37** [curiosum-dev/curious_messenger#1]
First of all I want to say thanks for taking the time to write this series of Blog Posts :)

The blog post for [part 3](https://curiosum.dev/blog/elixir-phoenix-liveview-messenger-part-3) doesn't mention that we need to add the plug [assign_user.ex](https://github.com/curiosum-dev/curious_messenger/blob/episode2/lib/curious_messenger_web/plugs/assign_user.ex) and to add to [PageController](https://github.com/curiosum-dev/curious_messenger/blob/episode2/lib/curious_messenger_web/controllers/page_controller.ex#L4) the line:

```elixir
plug CuriousMessengerWeb.AssignUser, preload: :conversations
```

Also the blog post mention that for [conversation.ex](https://github.com/curiosum-dev/curious_messenger/blob/episode2/lib/curious_messenger/chat/conversation.ex) we should add this code:

```elixir
schema "chat_conversations" do
  # ...
  has_many :conversation_members, ConversationMember
  has_many :conversations, through: [:conversation_members, :conversation]
end
```
But in instead the repo have [this code](https://github.com/curiosum-dev/curious_messenger/blob/episode2/lib/curious_messenger/chat/conversation.ex#L10-L11):

```elixir
# ....
has_many :conversation_members, ConversationMember, on_replace: :delete
has_many :users, through: [:conversation_members, :user]
```

Without this we get an exception:

```
[error] #PID<0.788.0> running CuriousMessengerWeb.Endpoint (connection #PID<0.786.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for #Ecto.Association.NotLoaded<association :conversations is not loaded> of type Ecto.Association.NotLoaded (a struct). This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.PrepareStream, DBConnection.Stream, HashDict, Range, Stream, MapSet, Date.Range, GenEvent.Stream, HashSet, Map, List, File.Stream, Function, IO.Stream
```

**Comment by vincentvanbush** [comment]
Hi @Exadra37 ,

Thanks for taking your time to notify us about the problem - I'll fix it ASAP and drop a comment here when done.

**Comment by vincentvanbush** [comment]
I've addressed both issues in an updated version of the post. Let us know if there's anything more that's causing problems (we'll have another look at this as well). Thanks again, and in case there's something else that requires our attention, just reopen this or create a new issue.

**Comment by Exadra37** [comment]
Thanks for the quick update of the article. You can read [this post](https://elixirforum.com/t/curious-messenger-phoenix-liveview-messenger-app/26683) in the Elixir forum for some more feedback.
